Second hw
BelitskyiAlexandr/spring-boot-intro pull request #2
Opened 2024-08-21 14:28 UTC by BelitskyiAlexandr

checkstyle problems

2024-08-21 14:29 UTC, BelitskyiAlexandr commented
Could you help me with checkstyle problems in autogen mapper.impl class?

2024-08-22 11:53 UTC, Elena-Bruyako requested changes
see comments

2024-08-22 11:53 UTC, Elena-Bruyako commented on pom.xml
>  					<linkXRef>false</linkXRef>
```suggestion
					<linkXRef>false</linkXRef>
					<sourceDirectories>src</sourceDirectories>
```

2024-08-22 13:15 UTC, Elena-Bruyako approved these changes
well done

2024-08-22 14:00 UTC, merged