jpa-hw done
BelitskyiAlexandr/spring-boot-intro pull request #4
Opened 2024-08-26 18:04 UTC by BelitskyiAlexandr

2024-08-27 11:08 UTC, Elena-Bruyako requested changes
see comments

2024-08-27 11:08 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/service/impl/BookServiceImpl.java
> +        book.setId(id);
```suggestion
       bookMapper.updateBookFromDto(createBookRequestDto, book);
```

2024-08-27 11:08 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/01-create-book-table.yaml
> +                  name: coverImage
```suggestion
                  name: cover_image
```

2024-08-27 13:59 UTC, BelitskyiAlexandr commented
could you tell me if it is ok that i used CreateBookRequestDto to update the book instead of creating a new dto?

There is simply little logic in creating a new identical dto, where only the name is different. Is it necessary to somehow change name in this case?

2024-08-27 14:48 UTC, BelitskyiAlexandr commented
There are some problems with my app. When I try to execute it, I get an exception:

```

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::                (v3.3.2)

2024-08-27T17:40:38.081+03:00  INFO 6992 --- [           main] c.e.bookshop.SpringBootIntroApplication  : Starting SpringBootIntroApplication using Java 17.0.2 with PID 6992 (D:\dyst\proj\spring\spring-boot-intro\target\classes started by ADMIN in D:\dyst\proj\spring\spring-boot-intro)
2024-08-27T17:40:38.087+03:00  INFO 6992 --- [           main] c.e.bookshop.SpringBootIntroApplication  : No active profile set, falling back to 1 default profile: "default"
2024-08-27T17:40:39.400+03:00  INFO 6992 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2024-08-27T17:40:39.496+03:00  INFO 6992 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 81 ms. Found 1 JPA repository interface.
2024-08-27T17:40:40.456+03:00  INFO 6992 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2024-08-27T17:40:40.479+03:00  INFO 6992 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-08-27T17:40:40.479+03:00  INFO 6992 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.26]
2024-08-27T17:40:40.601+03:00  INFO 6992 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-08-27T17:40:40.603+03:00  INFO 6992 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2432 ms
2024-08-27T17:40:40.915+03:00  INFO 6992 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2024-08-27T17:40:41.427+03:00  INFO 6992 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@45a1d057
2024-08-27T17:40:41.430+03:00  INFO 6992 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2024-08-27T17:40:42.540+03:00  INFO 6992 --- [           main] liquibase.changelog                      : Reading from bookshop_db.databasechangelog
2024-08-27T17:40:42.596+03:00  INFO 6992 --- [           main] liquibase.ui                             : Database is up to date, no changesets to execute
2024-08-27T17:40:42.600+03:00  INFO 6992 --- [           main] liquibase.changelog                      : Reading from bookshop_db.databasechangelog
2024-08-27T17:40:42.611+03:00  INFO 6992 --- [           main] liquibase.util                           : UPDATE SUMMARY
2024-08-27T17:40:42.612+03:00  INFO 6992 --- [           main] liquibase.util                           : Run:                          0
2024-08-27T17:40:42.612+03:00  INFO 6992 --- [           main] liquibase.util                           : Previously run:               1
2024-08-27T17:40:42.612+03:00  INFO 6992 --- [           main] liquibase.util                           : Filtered out:                 0
2024-08-27T17:40:42.613+03:00  INFO 6992 --- [           main] liquibase.util                           : -------------------------------
2024-08-27T17:40:42.613+03:00  INFO 6992 --- [           main] liquibase.util                           : Total change sets:            1
2024-08-27T17:40:42.614+03:00  INFO 6992 --- [           main] liquibase.util                           : Update summary generated
2024-08-27T17:40:42.644+03:00  INFO 6992 --- [           main] liquibase.lockservice                    : Successfully released change log lock
2024-08-27T17:40:42.647+03:00  INFO 6992 --- [           main] liquibase.command                        : Command execution complete
2024-08-27T17:40:42.770+03:00  INFO 6992 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2024-08-27T17:40:42.905+03:00  INFO 6992 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.5.2.Final
2024-08-27T17:40:42.958+03:00  INFO 6992 --- [           main] o.h.c.internal.RegionFactoryInitiator    : HHH000026: Second-level cache disabled
2024-08-27T17:40:43.462+03:00  INFO 6992 --- [           main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
2024-08-27T17:40:44.840+03:00  INFO 6992 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000489: No JTA platform available (set 'hibernate.transaction.jta.platform' to enable JTA platform integration)
2024-08-27T17:40:44.893+03:00 ERROR 6992 --- [           main] j.LocalContainerEntityManagerFactoryBean : Failed to initialize JPA EntityManagerFactory: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [books]
2024-08-27T17:40:44.894+03:00  WARN 6992 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [books]
2024-08-27T17:40:44.894+03:00  INFO 6992 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2024-08-27T17:40:44.907+03:00  INFO 6992 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2024-08-27T17:40:44.911+03:00  INFO 6992 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-08-27T17:40:44.929+03:00  INFO 6992 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-08-27T17:40:44.954+03:00 ERROR 6992 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [books]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1806) ~[spring-beans-6.1.11.jar:6.1.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[spring-beans-6.1.11.jar:6.1.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.11.jar:6.1.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.11.jar:6.1.11]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.11.jar:6.1.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spr [...]

2024-08-28 12:40 UTC, BelitskyiAlexandr commented
I changed to "create-drop" because I can work with it at least

2024-08-28 12:46 UTC, Elena-Bruyako requested changes
Please, ask your question in chat to provide more details about your problem

2024-08-28 12:46 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/mapper/BookMapper.java
> +    default Book updateBookFromDto(CreateBookRequestDto createBookRequestDto, Book book) {
```suggestion
    void updateBookFromDto(CreateBookRequestDto createBookRequestDto, @MappingTarget Book entity);
```

2024-08-28 12:46 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/mapper/BookMapper.java
> +    }
```suggestion
```

2024-08-28 18:26 UTC, okuzan approved these changes

2024-08-28 18:26 UTC, okuzan commented on src/main/java/com/example/bookshop/model/Book.java
> +@SQLRestriction(value = "is_deleted=false")
```suggestion
@SQLDelete(sql = "UPDATE books SET is_deleted = TRUE WHERE id = ?")
@SQLRestriction(value = "is_deleted = FALSE")
```

2024-08-28 18:26 UTC, okuzan commented on src/main/resources/db/changelog/changes/01-create-book-table.yaml
> +                    nullable: false
```suggestion
                    nullable: false
                    
```

2024-08-28 18:26 UTC, okuzan commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +
```suggestion
```

2024-08-29 14:25 UTC, merged