Search hw
BelitskyiAlexandr/spring-boot-intro pull request #5
Opened 2024-08-28 17:19 UTC by BelitskyiAlexandr

Have some problem. I do not know why, because I checked with the video and tried to debug. This value is nul from the beginning:
![image](https://github.com/user-attachments/assets/1da827ef-db2f-4aee-9a3a-07669a481302)

```

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::                (v3.3.2)

2024-08-28T20:15:32.678+03:00  INFO 16456 --- [           main] c.e.bookshop.SpringBootIntroApplication  : Starting SpringBootIntroApplication using Java 17.0.2 with PID 16456 (D:\dyst\proj\spring\spring-boot-intro\target\classes started by ADMIN in D:\dyst\proj\spring\spring-boot-intro)
2024-08-28T20:15:32.685+03:00  INFO 16456 --- [           main] c.e.bookshop.SpringBootIntroApplication  : No active profile set, falling back to 1 default profile: "default"
2024-08-28T20:15:35.886+03:00  INFO 16456 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2024-08-28T20:15:36.070+03:00  INFO 16456 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 170 ms. Found 1 JPA repository interface.
2024-08-28T20:15:38.632+03:00  INFO 16456 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2024-08-28T20:15:38.664+03:00  INFO 16456 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-08-28T20:15:38.665+03:00  INFO 16456 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.26]
2024-08-28T20:15:38.911+03:00  INFO 16456 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-08-28T20:15:38.914+03:00  INFO 16456 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 6039 ms
2024-08-28T20:15:39.729+03:00  INFO 16456 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2024-08-28T20:15:40.642+03:00  INFO 16456 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@5b251fb9
2024-08-28T20:15:40.646+03:00  INFO 16456 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2024-08-28T20:15:42.908+03:00  INFO 16456 --- [           main] liquibase.changelog                      : Reading from bookshop_db.databasechangelog
2024-08-28T20:15:43.047+03:00  INFO 16456 --- [           main] liquibase.ui                             : Database is up to date, no changesets to execute
2024-08-28T20:15:43.054+03:00  INFO 16456 --- [           main] liquibase.changelog                      : Reading from bookshop_db.databasechangelog
2024-08-28T20:15:43.070+03:00  INFO 16456 --- [           main] liquibase.util                           : UPDATE SUMMARY
2024-08-28T20:15:43.070+03:00  INFO 16456 --- [           main] liquibase.util                           : Run:                          0
2024-08-28T20:15:43.070+03:00  INFO 16456 --- [           main] liquibase.util                           : Previously run:               1
2024-08-28T20:15:43.070+03:00  INFO 16456 --- [           main] liquibase.util                           : Filtered out:                 0
2024-08-28T20:15:43.070+03:00  INFO 16456 --- [           main] liquibase.util                           : -------------------------------
2024-08-28T20:15:43.070+03:00  INFO 16456 --- [           main] liquibase.util                           : Total change sets:            1
2024-08-28T20:15:43.072+03:00  INFO 16456 --- [           main] liquibase.util                           : Update summary generated
2024-08-28T20:15:43.152+03:00  INFO 16456 --- [           main] liquibase.lockservice                    : Successfully released change log lock
2024-08-28T20:15:43.156+03:00  INFO 16456 --- [           main] liquibase.command                        : Command execution complete
2024-08-28T20:15:43.538+03:00  INFO 16456 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2024-08-28T20:15:43.795+03:00  INFO 16456 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.5.2.Final
2024-08-28T20:15:44.068+03:00  INFO 16456 --- [           main] o.h.c.internal.RegionFactoryInitiator    : HHH000026: Second-level cache disabled
2024-08-28T20:15:44.936+03:00  INFO 16456 --- [           main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
2024-08-28T20:15:46.904+03:00  INFO 16456 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000489: No JTA platform available (set 'hibernate.transaction.jta.platform' to enable JTA platform integration)
Hibernate: drop table if exists books
Hibernate: create table books (is_deleted bit not null, price decimal(38,2) not null, id bigint not null auto_increment, author varchar(255) not null, cover_image varchar(255), description varchar(255), isbn varchar(255) not null, title varchar(255) not null, primary key (id)) engine=InnoDB
Hibernate: alter table books add constraint UKkibbepcitr0a3cpk3rfr7nihn unique (isbn)
2024-08-28T20:15:47.097+03:00  INFO 16456 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2024-08-28T20:15:48.326+03:00  WARN 16456 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2024-08-28T20:15:49.874+03:00  INFO 16456 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8080 (http) with context path '/'
2024-08-28T20:15:49.900+03:00  INFO 16456 --- [           main] c.e.bookshop.SpringBootIntroApplication  : Started SpringBootIntroApplication in 18.363 seconds (process running for 19.462)
2024-08-28T20:16:12.637+03:00  INFO 16456 --- [nio-8080-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2024-08-28T20:16:12.638+03:00  INFO 16456 --- [nio-8080-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2024-08-28T20:16:12.640+03:00  INFO 16456 --- [nio-8080-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
Hibernate: insert into books (author,cover_image,description,is_deleted,isbn,price,title) values (?,?,?,?,?,?,?)
2024-08-28T20:16:25.056+03:00 ERROR 16456 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.NullPointerException: Cannot invoke "com.example.bookshop.repository.SpecificationProviderManager.getSpecificationProvider(String)" because "this.bookSpecificationProviderManager" is null] with root cause

java.lang.NullPointerException: Cannot invoke "com.example.bookshop.repository.SpecificationProviderManager.getSpecificationProvider(String)" because "this.bookSpecificationProviderManager" is null
	at com.example.bookshop.repository.book.BookSpecificationBuilder.build(BookSpecificationBuilder.java:20) ~[classes/:na]
	at com.example.bookshop.service.impl.BookServiceImpl.search(BookServiceImpl.java:59) ~[classes/:na]
	at com.example.bookshop.controller.BookController.search(BookController.java:55) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAc [...]

2024-08-29 08:21 UTC, MentorMateAcademy requested changes

2024-08-29 08:21 UTC, MentorMateAcademy commented on src/main/java/com/example/bookshop/repository/book/spec/AuthorSpecificationProvider.java
> +        return "author";
save string to constants and reuse it

2024-08-29 08:21 UTC, MentorMateAcademy commented on src/main/java/com/example/bookshop/repository/book/spec/PriceSpecificationProvider.java
> +                        return criteriaBuilder.between(root.get("price"), minPrice, maxPrice);
magic numbers

2024-08-29 08:21 UTC, MentorMateAcademy commented on src/main/java/com/example/bookshop/repository/book/spec/PriceSpecificationProvider.java
> +                        // if invalid - true
clear comments

2024-08-29 14:38 UTC, BelitskyiAlexandr commented
Please, help me with the problem:
https://github.com/BelitskyiAlexandr/spring-boot-intro/pull/5#issue-2492627522

2024-08-31 12:57 UTC, okuzan approved these changes

2024-08-31 13:31 UTC, merged